### PR TITLE
release of v4.0.1 html and copyright 2021

### PR DESCRIPTION
**Pull request by DLotts**

### CODE REVIEW

**Review by amihalik — COMMENTED** [review]
Looks good thanks!

**Review by adinancr — CHANGES_REQUESTED** [review]
All changes to the source code for the website should be made on the master branch, then generate the HTML version and commit the HTML to the asf-site branch. The changes in this PR do not seem to be consistent with the changes to the master branch (the PR seems to have changes just for the asf-site branch, e.g the copyright year). Is this the code generated by Jekyll from PR #12?

**Comment by DLotts** [comment]
@adinancr Yes that is what I intended to do.   I did cheat a bit as I converted all the copyrights to 2021 using sed on the asf-site.  I'll make sure it is generated that way with 2021 and no post processing should be needed.  Is that what you are seeing?

**Comment by adinancr** [comment]
@DLotts yes, that is what I was seeing. I think content/_includes/themes/apache/footer.html needs to be changed for the year. content/_config.yml might need to change as well to generate the correct baseurl and maybe change the url for rya to include https:// instead of http://. Thanks!!

**Pull request merged**
